integration tests
SmartCity-2022/Service-Bildungsportal pull request #48
Opened 2022-06-12 15:36 UTC by Hueppy

Closes #45 

Zum Ausführen:
`docker-compose up --exit-code-from cypress`

2022-06-12 21:05 UTC, Flamtky commented on test/cypress/package.json
> +  },
Einmal bitte `test` ergänzen.

2022-06-12 21:06 UTC, Flamtky requested changes
Ich finde es nett das du die Arbeit von mir übernehmen wolltest mit dem Tests starten etc.. Jedoch würde ich das mit den Tests anderes umsetzen unter anderem ohne Docker. Somit bitte einmal die Docker files entfernen. Und was soll die `testing.Dockerfile` genau machen?

2022-06-12 21:55 UTC, Hueppy commented
@Flamtky die Dateien wie das docker-compose Skript hatte ich jetzt hauptsächlich angelegt, damit ich eine Umgebung habe in der Ich die Tests laufen lassen kann.
`testing.Dockerfile` startet das frontend über npm, damit man von außen die URL des Backend ändern kann, im normalen `Dockerfile` ist die ja hardcoded drin.

2022-06-12 22:06 UTC, Flamtky commented
> @Flamtky die Dateien wie das docker-compose Skript hatte ich jetzt hauptsächlich angelegt, damit ich eine Umgebung habe in der Ich die Tests laufen lassen kann. `testing.Dockerfile` startet das frontend über npm, damit man von außen die URL des Backend ändern kann, im normalen `Dockerfile` ist die ja hardcoded drin.

Okay also wenn das Docker nur für dich ist zum testen, warum soll das dann in den `master`

2022-06-13 20:57 UTC, Flamtky commented on test/cypress/package.json
> +  },
Warum `"echo \"Error: no test specified\" && exit 1"`? Du hast doch `cypress:run` damit kann man doch die Tests starten oder nicht?

2022-06-13 20:57 UTC, Flamtky commented on test/cypress/package.json
> +  },
@Hueppy bitte klären

2022-06-13 23:55 UTC, Flamtky reviewed
Bitte vorherigen Review klären

2022-06-14 09:21 UTC, Flamtky approved these changes
👍

2022-06-14 09:21 UTC, merged