#4 introduce api specification draft
SmartCity-2022/Service-Bildungsportal pull request #5
Opened 2022-05-03 19:17 UTC by Hueppy

This is the first draft of the api between frontend and backend.
I also generated a markdown documentation, that is available in this projects wiki: 
https://github.com/SmartCity-2022/Service-Bildungsportal/wiki/api

2022-05-04 03:03 UTC, Flamtky requested changes
Siehe Kommentare im Request. (Alle Kommentare gelten auch für die anderen Requests)
**Zusatz:**
Falls die API hier ins Repo soll, bitte dann den Link zum [Documentation](https://github.com/SmartCity-2022/Documentation) Repository hinzufügen.

2022-05-04 03:03 UTC, Flamtky commented on doc/openapi.yaml
> +          description: "Institution not found"
Bei einer PUT Anfrage, kann es keine 404 geben da die Ressource erstellt wird wenn es diese nicht gibt. Vlt. ist es eher sinnvoll auf PATCH zu ändern.

2022-05-04 03:03 UTC, Flamtky commented on doc/openapi.yaml
> +              $ref: '#/components/schemas/Institution'
Vlt. die ID nicht angeben lassen beim Erstellen sondern per DB generieren lassen.

2022-05-04 03:03 UTC, Flamtky commented on doc/openapi.yaml
> +      responses:
Möglicherweise noch 409 ergänzen, falls die Ressource schon existiert

2022-05-04 13:26 UTC, Hueppy commented on doc/openapi.yaml
> +          description: "Institution not found"
Ich habe mich bei der Konzeption an der Beispiel "Petstore" API von swagger gehalten, dort wird auch für "update" Anfragen PUT benutzt und auch 404 zurückgegeben.
https://petstore.swagger.io/#/pet/updatePet

Aktuell bin ich mir nicht sicher welche Methode hier besser gewählt ist.

2022-05-04 15:55 UTC, Flamtky commented on doc/openapi.yaml
> +          description: "Institution not found"
PUT überscheibt halt die Ressource (im Regeln kann sie dann auch diese erstellen, falls es diese nicht gibt). [PATCH](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PATCH) ist halt extra fürs updaten.

2022-05-04 16:04 UTC, Flamtky commented on doc/openapi.yaml
> +          description: "Institution not found"
Wichtig ist auch das PATCH nicht alle Felder verlangt beim Updaten, der User sendet nur das was er erneuern will. PUT braucht das **ganze** neue Objekt zum überschreiben

2022-05-04 20:06 UTC, Hueppy commented on doc/openapi.yaml
> +          description: "Institution not found"
Ich glaube ich habe jetzt eine Lösung gefunden mit der Ich ganz zufrieden bin.

Die verschiedenen Objekte sind in zwei Objekte aufgeteilt, z.B. gibt es jetzt **LocationProperties** und **Location**. Dabei hat ist das Objekt mit der Endung **Properties** nur eine Art Sammlung der verschiedenen Attribute und das Objekt ohne Suffix erbt alle Attribute von dem **Properties** Objekt und markiert die benötigten als required.

Zudem habe ich die PUT-Operationen durch PATCH-Operationen ersetzt und diese PATCH-Operationen benutzen nun die **Properties** Objekte, wodurch es möglich ist eine Untermenge der Attribute zur Aktualisierung zu senden.

2022-05-04 20:07 UTC, Hueppy commented on doc/openapi.yaml
> +              $ref: '#/components/schemas/Institution'
Ich habe jetzt alle **Id**-Attribute als readOnly markiert, so werden diese bei einer **POST**-Operation ignoriert, in den **GET**-Operationen stehen diese jedoch noch zur Verfügung.

2022-05-04 20:12 UTC, Hueppy commented on doc/openapi.yaml
> +      responses:
Könntest du das hier nochmal etwas erläutern, vermutlich ist das durch eine der letzten Änderungen hinfällig geworden.

Zur Institution beispielsweise wird jetzt nur noch das **Name** Attribut während eines **POST** gesendet, die **Id** fiel nun weg. Und anhand des **Namens** ist eine Institution  nicht eindeutig zu erkennen, so gibt es z.B. mehr als eine "Erich-Kästner Grundschule" in Deutschland.

2022-05-04 20:13 UTC, Hueppy commented
@Flamtky ich wäre soweit mit den Issues durch, du kannst dir die Resolutions entsprechend angucken.

2022-05-04 21:36 UTC, Flamtky commented on doc/openapi.yaml
> +      responses:
Ja ist damit hinfällig geworden

2022-05-04 21:42 UTC, Flamtky requested changes

2022-05-04 21:42 UTC, Flamtky commented on doc/openapi.yaml
> +      responses:
Jedoch fehlen noch die 400 Fehler. Zum Beispiel was ist wenn der User keinen Namen dir sendet. Vlt. gibt es auch eine mindest oder maximal Länge?

2022-05-04 23:16 UTC, Hueppy commented on doc/openapi.yaml
> +      responses:
ich habe die Spezifikation jetzt noch um einige 400 und 403 Statuscodes erweitert.

2022-05-04 23:51 UTC, Flamtky commented on doc/openapi.yaml
> +      responses:
Wenn du 403 müsstest du auch 401 ergänzen. 401 passiert wenn der User sich nicht versucht du autorisieren, 403 passiert ja nur wenn er es versucht nur mit zu wenig Rechten (Admin, User)

2022-05-05 11:05 UTC, Hueppy commented on doc/openapi.yaml
> +      responses:
401 habe ich nun hinzugefügt

2022-05-05 11:32 UTC, Flamtky approved these changes

2022-05-05 11:32 UTC, merged